name: RSpec Test CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/rspec-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/rspec-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: cash_register
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cash_register_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10ms
          --health-timeout 500ms
          --health-retries 15
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          working-directory: backend
          bundler-cache: true

      - name: Setup Database
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB_NAME: cash_register_db
          POSTGRES_PASSWORD: password
          POSTGRES_USERNAME: cash_register
          POSTGRES_PORT: 5432
          RAILS_ENV: test
          PARALLEL_TEST_PROCESSORS: 2
        run: |
          cd backend
          cp config/database.test.yml config/database.yml
          bundle exec rake parallel:setup

      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB_NAME: cash_register_db
          POSTGRES_PASSWORD: password
          POSTGRES_USERNAME: cash_register
          POSTGRES_PORT: 5432
          RAILS_ENV: test
          PARALLEL_TEST_PROCESSORS: 2
        run: |
          cd backend
          bundle exec rake parallel:spec
