name: RSpec Test CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/rspec-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/rspec-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: cash_register
          POSTGRES_PASSWORD: cash_register
          POSTGRES_DB: cash_register_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10ms
          --health-timeout 500ms
          --health-retries 15
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          working-directory: backend
          bundler-cache: true

      - name: Setup DB and Run Tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          POSTGRES_DB: cash_register_test
          POSTGRES_PASSWORD: cash_register
          POSTGRES_USERNAME: cash_register
          RAILS_ENV: test
          PARALLEL_TEST_PROCESSORS: 2
        run: |
          bin/rails parallel:setup
          bin/rails parallel:spec
